####################################
# YoloV5模型权重路径
weight:  "weights/AppleBest.pt"
# 输入图像的尺寸
input_size: 640
# 类别个数
class_num: 1
# 标签名称
class_name: ['apple']
# 阈值设置
threshold:
  iou: 0.45
  confidence: 0.6
# 计算设备
# - cpu
# - 0 <- 使用GPU
device: '0'